# Author: Aniruddha Gokhale
# Vanderbilt University
# Created Nov 2017
#
# For Cloud Computing class
#
# Docker build file for ZMQ Client-Server
#

# First, use the latest ubuntu image
FROM ubuntu:latest
#

# Now install the needed python and other packages
RUN apt-get -y update && apt-get install -y net-tools iputils-ping python

# The following may not be needed but we let it be there.
RUN apt-get install -y python-dev python-pip
RUN python -m pip install --upgrade pip

# Install the zeromq package
RUN apt-get install -y python-zmq

#
# Next, copy the files needed to run the map-reduce master
COPY client.py /root/
COPY server.py /root/

#
# Run a command shell
CMD /bin/bash
