# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: discovery.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64iscovery.proto\":\n\x0bRegisterReq\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x11\n\ttopiclist\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\t\"\x1e\n\x0cRegisterResp\x12\x0e\n\x06result\x18\x01 \x01(\t\"\x0c\n\nIsReadyReq\"\x1c\n\x0bIsReadyResp\x12\r\n\x05reply\x18\x01 \x01(\x08\"(\n\x13LookupPubByTopicReq\x12\x11\n\ttopiclist\x18\x01 \x01(\t\"\x16\n\x14LookupPubByTopicResp\"\xa4\x01\n\x0c\x44iscoveryReq\x12\x1b\n\x08msg_type\x18\x01 \x01(\x0e\x32\t.MsgTypes\x12$\n\x0cregister_req\x18\x02 \x01(\x0b\x32\x0c.RegisterReqH\x00\x12\x1f\n\x08is_ready\x18\x03 \x01(\x0b\x32\x0b.IsReadyReqH\x00\x12%\n\x05topic\x18\x04 \x01(\x0b\x32\x14.LookupPubByTopicReqH\x00\x42\t\n\x07\x43ontent\"\xa8\x01\n\rDiscoveryResp\x12\x1b\n\x08msg_type\x18\x01 \x01(\x0e\x32\t.MsgTypes\x12&\n\rregister_resp\x18\x02 \x01(\x0b\x32\r.RegisterRespH\x00\x12 \n\x08is_ready\x18\x03 \x01(\x0b\x32\x0c.IsReadyRespH\x00\x12%\n\x04resp\x18\x04 \x01(\x0b\x32\x15.LookupPubByTopicRespH\x00\x42\t\n\x07\x43ontent*`\n\x08MsgTypes\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0c\n\x08REGISTER\x10\x01\x12\x0b\n\x07ISREADY\x10\x02\x12\x17\n\x13LOOKUP_PUB_BY_TOPIC\x10\x03\x12\x13\n\x0fLOOKUP_ALL_PUBS\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'discovery_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_MSGTYPES']._serialized_start=559
  _globals['_MSGTYPES']._serialized_end=655
  _globals['_REGISTERREQ']._serialized_start=19
  _globals['_REGISTERREQ']._serialized_end=77
  _globals['_REGISTERRESP']._serialized_start=79
  _globals['_REGISTERRESP']._serialized_end=109
  _globals['_ISREADYREQ']._serialized_start=111
  _globals['_ISREADYREQ']._serialized_end=123
  _globals['_ISREADYRESP']._serialized_start=125
  _globals['_ISREADYRESP']._serialized_end=153
  _globals['_LOOKUPPUBBYTOPICREQ']._serialized_start=155
  _globals['_LOOKUPPUBBYTOPICREQ']._serialized_end=195
  _globals['_LOOKUPPUBBYTOPICRESP']._serialized_start=197
  _globals['_LOOKUPPUBBYTOPICRESP']._serialized_end=219
  _globals['_DISCOVERYREQ']._serialized_start=222
  _globals['_DISCOVERYREQ']._serialized_end=386
  _globals['_DISCOVERYRESP']._serialized_start=389
  _globals['_DISCOVERYRESP']._serialized_end=557
# @@protoc_insertion_point(module_scope)
